/**
 * generate-env.js
 * ─────────────────────────────────────────────────────────────
 * This script runs automatically on Netlify BEFORE the site
 * goes live. It reads your API keys from Netlify's environment
 * variable dashboard and writes them into js/firebase-env.js
 *
 * YOU NEVER NEED TO EDIT THIS FILE.
 * Just paste your keys into the Netlify dashboard (Step 3).
 * ─────────────────────────────────────────────────────────────
 */

const fs   = require("fs");
const path = require("path");

/* Read every key from Netlify's environment */
const {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID,
} = process.env;

/* Warn loudly if any required key is missing */
const required = {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
};

let missing = false;
for (const [name, value] of Object.entries(required)) {
  if (!value) {
    console.error(`[generate-env] ❌  Missing environment variable: ${name}`);
    missing = true;
  }
}
if (missing) {
  console.error("[generate-env] Add the missing variables in Netlify → Site settings → Environment variables.");
  process.exit(1);
}

/* Build the file content */
const content = `// ⚠️  AUTO-GENERATED by generate-env.js at build time.
// Do NOT edit this file manually — changes will be overwritten on next deploy.
// To change values, update them in Netlify → Site settings → Environment variables.

const firebaseConfig = {
  apiKey:            "${FIREBASE_API_KEY}",
  authDomain:        "${FIREBASE_AUTH_DOMAIN}",
  projectId:         "${FIREBASE_PROJECT_ID}",
  storageBucket:     "${FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID}",
  appId:             "${FIREBASE_APP_ID}",${
    FIREBASE_MEASUREMENT_ID
      ? `\n  measurementId:     "${FIREBASE_MEASUREMENT_ID}",`
      : ""
  }
};

export default firebaseConfig;
`;

/* Write to js/firebase-env.js */
const outputPath = path.join(__dirname, "js", "firebase-env.js");
fs.writeFileSync(outputPath, content, "utf8");

console.log("[generate-env] ✅  js/firebase-env.js generated successfully.");
